#!/usr/bin/env bash

# weird names and file copies on this one
# because we are going to keep the file separate
# to do some fancy process control.

traprestart() {
  $0 "$$" &
  exit 0
}

trap traprestart HUP TERM INT
echo
sleep 1

which xrls1 || cp /usr/local/bin/sec /usr/local/bin/xrls1

xrls1 -input /var/log/messages -input /var/log/secure -input /var/log/syslog -input /var/log/auth.log -input /var/log/httpd/access.log -input /var/log/nginx/access.log -input /var/log/apache2/access.log -input /var/log/access.log -conf /opt/system-sec.cfg
